# Generated by Django 5.2 on 2025-04-15 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assignment',
            table='assignments',
        ),
        migrations.AlterModelTable(
            name='attempt',
            table='attempts',
        ),
        migrations.AlterModelTable(
            name='coursetopic',
            table='course_topics',
        ),
        migrations.AlterModelTable(
            name='lab',
            table='labs',
        ),
        migrations.AlterModelTable(
            name='subtopic',
            table='subtopics',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
