# Generated by Django 5.2 on 2025-04-15 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_assignment_table_alter_attempt_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='id',
        ),
        migrations.RemoveField(
            model_name='coursetopic',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='attempt',
            name='attempt_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='topic_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='lab',
            name='lab_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='subtopic_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='university.lab'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='university.assignment'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='university.user'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='subtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='university.subtopic'),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='university.coursetopic'),
        ),
        migrations.AlterModelTable(
            name='assignment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='attempt',
            table=None,
        ),
        migrations.AlterModelTable(
            name='coursetopic',
            table=None,
        ),
        migrations.AlterModelTable(
            name='lab',
            table=None,
        ),
        migrations.AlterModelTable(
            name='subtopic',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
