# Generated by Django 5.2 on 2025-04-15 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_remove_assignment_academic_year_remove_assignment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.lab'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.assignment'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.user'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='subtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.subtopic'),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.coursetopic'),
        ),
        migrations.AlterModelTable(
            name='assignment',
            table='assignments',
        ),
        migrations.AlterModelTable(
            name='attempt',
            table='attempts',
        ),
        migrations.AlterModelTable(
            name='coursetopic',
            table='course_topics',
        ),
        migrations.AlterModelTable(
            name='lab',
            table='labs',
        ),
        migrations.AlterModelTable(
            name='subtopic',
            table='subtopics',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
